on: 
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubunto-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 8.0.x
      - run: cd Test && dotnet test
